### ISSUE TITLE
kein open/Close State

### ISSUE THREAD

**Issue by Beliar-666** [Pittini/iobroker-Fensterauswertung#1]
Hallo Pittini,
Hat sich offensichtlich erledigt, nach einem erneuten Zuweisen und Scriptneustart hat er diese Sensoren jetzt doch übernommen

Ich habe dein Script grad mal getestet und finde es sehr klasse. Allerdings habe ich ein Problem mit 2 homematic Sensoren.  Die geben statt open/close im State eben true für open und false für geschlossen. Auf diese reagiert das Script leider nicht. Lässt sich da im Script etwas ändern oder erweitern?

Also als Datenpunkte hat er mir diese Sensoren mit angelegt. Also generell erkennen tut er diese.

Grüssle

**Comment by Pittini** [comment]
Meine Xiaomi Sensoren melden nur true/false und daraus ist das Skript entstanden, also grad diese beiden states funktionieren 100%, wie Du ja inzwischen gemerkt hast ;) Ich mach dicht.
