### ISSUE TITLE
Benechrichtigungshäufigkeit

### ISSUE THREAD

**Issue by n3roGit** [Pittini/iobroker-Fensterauswertung#10]
Die Warnung alle X Minuten bei geöffneten Fenster exponentiell verlängern. Gerade bei warmen Temperaturen möchte man manche Fenster ja gerne offen haben.
Da wäre etwa wie 30 min, 1 h, 2h , keine weitere optimal.

**Comment by Pittini** [comment]
Klar will man offene Fenster im Sommer. An sich sind ja zwei Varianten schon integriert, entweder man schaltet in der Zeit die Benachrichtigung einfach ab (so hab ich das hier zuhause) oder man wählt statt zyklische Meldung einmalige Meldung. Eigentlich meine ich das sollte genügen, außer Du kannst mich vom Gegenteil überzeugen.

**Comment by n3roGit** [comment]
Das ist auch bereits ganz gut soweit. Es wäre einfach eine schöne Funktion die Benachrichtigung nicht die ganze Zeit zu bekommen. Oder eben einen Counter für die maximale Anzahl an Benachrichtigungen anzugeben.

**Comment by Pittini** [comment]
Counter implementiert mit V1.5.0
