### ISSUE TITLE
AlsoMsgWinOpenClose nach Zeit X

### ISSUE THREAD

**Issue by n3roGit** [Pittini/iobroker-Fensterauswertung#11]
AlsoMsgWinOpenClose erst bei einer Änderungszeit von z.b. einer Minute ansagen. Oft will man ja nur "eben" was von draußen holen oder ähnliches.

**Comment by Pittini** [comment]
Da ich mal nicht annehme dass Du durchs Fenster krabbelst um was zu holen, nehm ich an das betrifft diese mannshohen Fenstertüren die z.B. auf die Veranda oder den Balkon führen? Das ist so ein "Sonderfall" da das Skript ja eigentlich auf Fenster spezialisiert ist. Aber da es den Wunsch auch bei kurzem öffnen des Fensters geben kann hab ich das mal integriert, aber anders. Es betrifft nicht nur wie vorgeschlagen die MsgWinOpenClose, sondern das Skript wird alle Aktionen innerhalb einer Einstellbaren Zeit ignorieren wenn der Zustand des Sensors nach dieser Zeit, derselbe ist als der davor. Kommt mit dem nächsten Update, bei dem noch etliche andere Adds drin sind.

**Comment by Pittini** [comment]
Implementiert mit V 1.5.0
