### ISSUE TITLE
Gekippt

### ISSUE THREAD

**Issue by n3roGit** [Pittini/iobroker-Fensterauswertung#12]
Super Job mit der neuen Version =)

Echt tolle neue Funktionen!!

Was ich mich nur frage... Wie muss ich das mit den gekippten Fenster konfigurieren? Aus meinem Verständnis heraus müsste ich eigentlich an jedes Fenster einen zweiten Sensor backen und diesem eine andere Funktion zuordnen. z.B. "FensterKipp". Aus der Doku geht das aber nicht hervor ^^

**Comment by Pittini** [comment]
Wenn möglich bitte solche Fragen[ im Forum](https://forum.iobroker.net/topic/31674/vorlage-generisches-fensteroffenskript-vis/111) klären. Issues nur bei Bugs oder Feature Requests.
Zu Deiner Frage. Geht nicht wenn Du nicht die entprechenden Sensoren hast. Gibt sogenannte Drehgriffsensoren, die melden zu/offen/gekippt je nach Stellung des Griffes. Für die ist das gedacht. Und wenn 3malige Erwähnung in der Doku nicht reicht, weis ich auch ned.

4.  RoomsWithOpenWindows: Eine Textliste von Räumen mit geöffneten Fenstern und deren Anzahl, sowie die Untermenge der davon gekippten Fenster (Funktioniert natürlich nur wenn entsprechende Sensoren verwendet werden die gekippt als Status melden). Sinnvoll für Kurzfassungsanzeigen in Vis.
   5.  RoomsWithTiltedWindows: Eine Textliste von Räumen mit gekippten Fenstern und deren Anzahl. Sinnvoll für Kurzfassungsanzeigen in Vis (Funktioniert natürlich nur wenn entsprechende Sensoren verwendet werden die gekippt als Status melden).
