### ISSUE TITLE
Verschiedene Magnetsensoren

### ISSUE THREAD

**Issue by stephan2k** [Pittini/iobroker-Fensterauswertung#13]
Hallo,

ich habe verschiedene Magnetsensoren:
- Innogy: zeigt den Status des Fensters bei **IsOpen** mit TRUE / FALSE ein
- Aqara via conbee / deconz: Status bei **Open** mit TRUE / FALSE
- Aqara via Xiaomi Gateway: Status bei **State** mit TRUE / FALSE

Mit dem Script werden mir nur die Fenster die mit dem Innogy Magnetsensor hinterlegt sind.
Mach ich etwas falsch?
![fenster_1](https://user-images.githubusercontent.com/38348904/80274801-4747be80-86dd-11ea-9468-7a31bfce6a0a.png)
![fenster_2](https://user-images.githubusercontent.com/38348904/80274804-4878eb80-86dd-11ea-8ffa-3410735eaf82.png)

**Comment by Pittini** [comment]
Grundsätzlich isses dem Skript egal welche Sensoren, auch gemischt, verwendet werden. Xiaomi mit Gateway geht auf jeden Fall, die hab ich selber. Was ich grad nicht versteh ist, Du zeigst mir Datenpunkte von 3 Räumen, im Bild sind aber 5, wobei da wieder das Eg Gästeklo nicht dabei ist. Und welche Sensoren verwenden die beiden Räume zu denen Du mir den Datenpunkt nicht gezeigt hast? Nur von den beiden Screens kann ich aber eh nix erkennen, poste mal das Log vom Skript bitte. Und nen Screen vom geöffneten Skriptchannel unter Javascript.0.FensterUeberwachung. Und Frage: Hast Du die js Instanz nach dem Anlegen der Funktionen mal neu gestartet?

**Comment by stephan2k** [comment]
Hi,
bei der Installation von der GIT Datei  bekomme ich folgenden Fehler:

`$ ./iobroker url "https://github.com/Pittini/iobroker-Fensterauswertung.git"
install https://github.com/Pittini/iobroker-Fensterauswertung/tarball/6c0dfda09cc0a31925ac296e50f568adb1556f3f
NPM version: 6.13.4
npm install https://github.com/Pittini/iobroker-Fensterauswertung/tarball/6c0dfda09cc0a31925ac296e50f568adb1556f3f --unsafe-perm --loglevel error --prefix "/opt/iobroker" (System call)
npm
 ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: https://github.com/Pittini/iobroker-Fensterauswertung/tarball/6c0dfda09cc0a31925ac296e50f568adb1556f3f.npm ERR!
 package.json npm can't find a package.json file in your current directory.

npm ERR!
 A complete log of this run can be found in:npm ERR!     /root/.npm/_logs/2020-04-26T07_06_04_165Z-debug.log
ERROR: host.iobroker Cannot install https://github.com/Pittini/iobroker-Fensterauswertung/tarball/6c0dfda09cc0a31925ac296e50f568adb1556f3f: 1
ERROR: process exited with code `25``

**Comment by Pittini** [comment]
> Hi,
> bei der Installation von der GIT Datei bekomme ich folgenden Fehler:

Seufz. Da hattest es doch schon installiert, sonst hättest ja den Screenshot im ersten Post nicht machen können. Und dann denkst mal drüber nach was Du jetzt anders gemacht hast, bzw. warum Du Dich nicht an die Anleitung gehalten hast.
Das ist ein Skript und kein Adapter, also kannst es auch nicht als Adapter installieren.
