### ISSUE TITLE
Anlage der DP unter 0_userdata.0

### ISSUE THREAD

**Issue by CKMartens** [Pittini/iobroker-Fensterauswertung#14]
Wäre es möglich die DPs auch unter 0_userdata anzulegen (mit Hilfe von z.B: Mic Skript 
https://github.com/Mic-M/iobroker.createUserStates)?

Mir gefällt Dein Skript sehr gut und ich würde aber gerne meine bisherige Struktur der eigenen DPs weiter führen.

**Comment by Pittini** [comment]
Du kannst das Projekt gerne forken und es Dir einbauen. Ich werden 0_Userdata erst dann unterstützen wenn es auch native ohne Extraskript implementiert ist, halbgare Sachen mag ich nicht. Abgesehen davon bin ich der Meinung das Skriptdaten eben Skriptdaten und keine Userdaten sind. Und wenn ich das Skript, wie mittelfristig geplant, zum Adapter mach, hats eh nen eigenen Channel.

**Comment by CKMartens** [comment]
Danke für Deine Antwort.

Ich werde dann mal auf Deinen Adapter warten ;)

**Comment by Pittini** [comment]
> Ich werde dann mal auf Deinen Adapter warten ;)

Ich schrieb mittelfristig. Das sind Monate, nur zur Info.
