### ISSUE TITLE
Geöffnet/Geschlossen Meldung bei mehreren Fenstern pro Raum

### ISSUE THREAD

**Issue by n3roGit** [Pittini/iobroker-Fensterauswertung#15]
Momentan wird bei Räumen mit mehreren Fenstern für jeden öffnen oder schließen eine Benachrichtigung ausgegeben. Wenn ich Lüste und zwei Fenster öffne gibts auch zwei Benachrichtigungen. In diesem Fall wäre eine Nachricht ausreichend.

Alternativ könnte man die Aussage auch wie folgt ändern "1 von 2 Fenstern im Büro geöffnet"

**Comment by Pittini** [comment]
> Wenn ich Lüste und zwei Fenster öffne gibts auch zwei Benachrichtigungen. In diesem Fall wäre eine Nachricht ausreichend.

Das war so vor dem gekippt einbau und bleibt auch so weil es jetzt eben verschiedene Stati beim öffnen geben kann. Wenn Du es trotzdem anders willst, versetze die Klammer von Zeile 495 nach Zeile 506

**Comment by n3roGit** [comment]
Danke für die schnelle Reaktion!

Meinst du diese Stelle?

zip--
          if (SensorVal[x] == "open") {
                if (logging) log(TempRoom + " Fenster geöffnet");
                if (SendOpenCloseMsg[TempRoomIndex]) Meldung(ReplaceChars(TempRoom) + " Fenster geöffnet!");
                if (UseEventLog) WriteEventLog(ReplaceChars(TempRoom) + " Fenster geöffnet!");
            }
            else if (SensorVal[x] == "tilted") {
                if (logging) log(TempRoom + " Fenster gekippt");
                if (SendOpenCloseMsg[TempRoomIndex]) Meldung(ReplaceChars(TempRoom) + " Fenster gekippt!");
                if (UseEventLog) WriteEventLog(ReplaceChars(TempRoom) + " Fenster gekippt!");
            };
            
        };

        if (RoomOpenWindowCount[TempRoomIndex] == 1) {
            log("SendWarnMsg=" + SendWarnMsg[TempRoomIndex] + " TempRoomIndex=" + TempRoomIndex)
            Laufzeit[TempRoomIndex] = 0;
--zip

Ich bin in JavaScript leider nicht so fit^^


Ich hab dein Script auch mal versucht für Bewegungsmelder zu missbrauchen. Einfach um für jeden Raum einen DP zu haben ob Bewegung ist oder nicht. Das scheint sogar zu funktionieren. Lediglich der HTML Tabel wird nicht erstellt. Da suche ich gerade noch meinen Fehler.

**Comment by Pittini** [comment]
> Ich bin in JavaScript leider nicht so fit^^

Und was hat das damit zu tun ein einzelnes Zeichen von einer genau angegebenen Position zu einer anderen angegebenen Position zu versetzen?

>Ich hab dein Script auch mal versucht für Bewegungsmelder zu missbrauchen. Einfach um für jeden Raum einen DP zu haben ob Bewegung ist oder nicht. Das scheint sogar zu funktionieren. Lediglich der HTML Tabel wird nicht erstellt. Da suche ich gerade noch meinen Fehler.

Klar geht das iwie, dem Skript isses ja prinzipiell egal was da jetzt true oder false meldet. Mußt halt dafür sorgen dass die beiden Skripte sich nicht in die Haare kriegen was das Skriptverzeichnis und die Funktionsbezeichnung angeht. Und die Lüftungswarnung etc. sind natürlich für die Katz.
