### ISSUE TITLE
Lüftungserinnerung

### ISSUE THREAD

**Issue by n3roGit** [Pittini/iobroker-Fensterauswertung#16]
![image](https://user-images.githubusercontent.com/8565847/80828893-5d2a1780-8be6-11ea-957e-8ee03e60f281.png)

Moin moin,

ich hab das Gefühl das die Lüftungserinnernung nocht nicht ganz stimmt. z.B. die Küche war vor ~40 Minuten mindestens 45 Minuten auf. Trotzdem meint das Script, dass gelüftet werden muss.

Beste Grüße

**Comment by Pittini** [comment]
Skriptversion?

**Comment by n3roGit** [comment]
1.5

**Comment by Pittini** [comment]
> 1.5

Nimm mal die aktuelle
