### ISSUE TITLE
Request: doorstatus

### ISSUE THREAD

**Issue by Sarzeau** [Pittini/iobroker-Fensterauswertung#18]
Hi Pittini,

vielen Dank für Dein Script, tolle Arbeit!
Habe mir eine zweite Instanz für die Türen gebastelt. Das sind ja nur wenige, nur die Außentüren haben Sensoren. 
Könnte man (könntest Du..) das nicht in einem Script mit getrennter Auswertung zusammenfassen, also pro Raum z.B. 2 Fenster 1 Tür? Getrennt nach Funktion? Dann könnte man sich das auch zusammen anzeigen / ansagen lassen.
Gruß
Thilo

**Comment by Pittini** [comment]
Erweiterung auf Türen wird kommen, ist in Planung, wird aber noch etwas dauern da erst mal die Großbaustelle am Timerskript abgeschlossen werden muß.

**Comment by Sarzeau** [comment]
Super, dann warte ich mal ab! Timerskript ist auch ein tolles Projekt.
LG TT
