### ISSUE TITLE
Script nach einer weile auf Gelb !?!

### ISSUE THREAD

**Issue by D3ltorohd** [Pittini/iobroker-Fensterauswertung#19]
Hallo Pittini,

erst mal vielen Dank für das Klasse Script. Wollte mir was für die VIS basteln und bin dann auf deine Lösung gestoßen, Klasse. Kann ich gleich für Alexa und Co mit verwenden.

Nun lief das soweit, die DP's wurden erstellt. Nur nachdem man das Script startet und ich dann mal wieder reinschaue ist es Gelb. Das habe ich dazu in der Log gefunden..

`

javascript.0 | 2020-06-21 20:16:05.093 | error | (13557) at processTimers (internal/timers.js:492:7)
-- | -- | -- | --
javascript.0 | 2020-06-21 20:16:05.093 | error | (13557) at listOnTimeout (internal/timers.js:551:17)
javascript.0 | 2020-06-21 20:16:05.092 | error | (13557) at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:2039:34)
javascript.0 | 2020-06-21 20:16:05.092 | error | (13557) at Object.<anonymous> (script.js.VIS.Fensterstatus:740:29)
javascript.0 | 2020-06-21 20:16:05.092 | error | (13557) at CheckWindow (script.js.VIS.Fensterstatus:505:54)
javascript.0 | 2020-06-21 20:16:05.092 | error | (13557) at Meldung (script.js.VIS.Fensterstatus:209:21)
javascript.0 | 2020-06-21 20:16:05.091 | error | (13557) Error in callback: ReferenceError: Say is not defined
javascript.0 | 2020-06-21 20:16:05.090 | info | (13557) script.js.VIS.Fensterstatus: Reaching Meldung, msg= Schlafzimmer Fenster geöffnet!
javascript.0 | 2020-06-21 20:16:05.090 | info | (13557) script.js.VIS.Fensterstatus: Schlafzimmer Fenster geöffnet
javascript.0 | 2020-06-21 20:16:05.089 | info | (13557) script.js.VIS.Fensterstatus: RoomOpenWindowCount für Schlafzimmer=2

`
Kommt das alles wegen dem ?

ReferenceError: Say is not defined

Grüße,

**Comment by Pittini** [comment]
Konfigurationsfehler. UseSay in den Einstellungen auf false setzen wie gefordert.

**Comment by D3ltorohd** [comment]
Danke, muss ich übersehen haben. Läuft !!! Vielen Dank !!!
