### ISSUE TITLE
javascript error - bei Zustandswechsel

### ISSUE THREAD

**Issue by ghost** [Pittini/iobroker-Fensterauswertung#2]
Hallo, 

ich habe bestimmt etwas verkehrt gemacht und hänge fest.
Wenn ich das Script starte wird alles normal angezeigt ob offen oder geschlossen...

![Unbenannt-1](https://user-images.githubusercontent.com/62837358/77848661-a392ed80-71c6-11ea-8276-b6981a038005.jpg)

Wenn ich jedoch ein Fester öffne dann kommt im Script ein Error und es stoppt...

![Unbenannt-2](https://user-images.githubusercontent.com/62837358/77848721-27e57080-71c7-11ea-8958-517e33fed50b.jpg)

![Unbenannt-3](https://user-images.githubusercontent.com/62837358/77848768-7f83dc00-71c7-11ea-9656-174a71f23a7b.jpg)

![Unbenannt-4](https://user-images.githubusercontent.com/62837358/77848808-b659f200-71c7-11ea-9e26-b1af622309e6.jpg)

Wenn du noch weitere Informationen benötigst dann schreibe bitte was...

Danke für dein Script sowie deine Hilfe.
Henri

**Comment by totocotonio** [comment]
Hi,
ich kann den Fehler bestätigen

Funktioniert bei mir auch nicht.


javascript.0 | 2020-03-29 17:24:08.553 | error | (6744) at Timer.processTimers (timers.js:223:10)
-- | -- | -- | --
javascript.0 | 2020-03-29 17:24:08.553 | error | (6744) at listOnTimeout (timers.js:263:5)
javascript.0 | 2020-03-29 17:24:08.553 | error | (6744) at tryOnTimeout (timers.js:300:5)
javascript.0 | 2020-03-29 17:24:08.553 | error | (6744) at ontimeout (timers.js:438:13)
javascript.0 | 2020-03-29 17:24:08.553 | error | (6744) at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1984:34)
javascript.0 | 2020-03-29 17:24:08.553 | error | (6744) at Object.<anonymous> (script.js.common.Lichter.Fensterauswertung:280:25)
javascript.0 | 2020-03-29 17:24:08.552 | error | (6744) at Meldung (script.js.common.Lichter.Fensterauswertung:115:17)
javascript.0 | 2020-03-29 17:24:08.552 | error | (6744) Error in callback: ReferenceError: Say is not defined
javascript.0 | 2020-03-29 17:24:08.543 | error | (6744) at Timer.processTimers (timers.js:223:10)
javascript.0 | 2020-03-29 17:24:08.543 | error | (6744) at listOnTimeout (timers.js:263:5)
javascript.0 | 2020-03-29 17:24:08.543 | error | (6744) at tryOnTimeout (timers.js:300:5)
javascript.0 | 2020-03-29 17:24:08.543 | error | (6744) at ontimeout (timers.js:438:13)
javascript.0 | 2020-03-29 17:24:08.543 | error | (6744) at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1984:34)
javascript.0 | 2020-03-29 17:24:08.543 | error | (6744) at Object.<anonymous> (script.js.common.Lichter.Fensterauswertung:280:25)
javascript.0 | 2020-03-29 17:24:08.543 | error | (6744) at Meldung (script.js.common.Lichter.Fensterauswertung:115:17)
javascript.0 | 2020-03-29 17:24:08.542 | error | (6744) Error in callback: ReferenceError: Say is not defined

**Comment by ghost** [comment]
Hallo, stelle mal...

UseEventLog auf false

bei mir geht es dann.

**Comment by Pittini** [comment]
Für beide Fehler gilt, Beschreibung nicht befolgt, Zeile 18 und 19 auf false stellen wie es auch direkt daneben steht.
