### ISSUE TITLE
CPU Last

### ISSUE THREAD

**Issue by totocotonio** [Pittini/iobroker-Fensterauswertung#20]
Hi,
ich habe das script jetzt einige Tage am laufen.

Im Log sind keine Fehler.

Aber was mir jetzt aufgefallen ist, das wenn ich das Script aktiviere der Javascript Adapter  auf über 10000 Eingänge und 8000 Ausgänge hochläuft.

Desweitern geht die CPU Last auf über 50 %.

Wenn ich das Script wieder deaktiviere ist alles wieder normal.

Last liegt dann bei ca. 5%

**Comment by Pittini** [comment]
Ja was soll ich da jetzt sagen/machen? Bei mir ist das nicht so. Wenn Du nicht immer ein Issue aufmachen würdest und sowas im Forumthread mal ansprechen würdest, könnten die anderen User evtl. was dazu sagen.

**Comment by totocotonio** [comment]
ok,
habe die frage im Forum gestellt.
