### ISSUE TITLE
Diskrepanz Raum/Wohnung

### ISSUE THREAD

**Issue by Dragon0501** [Pittini/iobroker-Fensterauswertung#25]
Ich habe in meinem Badezimmer das geöffnet. Im Badezimmer wird auch ein geöffnetes Fenster angezeigt. Im Hauptverzeichnis ist der DP AllWindowsClosed jedoch weiterhin true. Es wird also das Zimmer korrekt kalkuliert, die Gesamtübersicht wird jedoch nicht aktualisiert, weil auch die Aufzählung verändert sich nicht. Die Version 1.6.6 funktioniert. In der 1.6.7 Ist der Fehler vorhanden.

**Comment by Pittini** [comment]
Kann ich leider nicht reproduzieren (siehe Screenshot). Gib mir mal bitte folgendes:
Screen der Summenwerte des Skriptes (also genau das was ich angehängt hab, nur eben von Dir) und vom Bad bei geöffnetem Badfenster. Zusätzlich Startlog bei geöffnetem Badfenster.
![2020-10-23 16_00_38-Window](https://user-images.githubusercontent.com/51408942/97013544-75517280-1549-11eb-933a-c00050ad43a5.png)

**Comment by Dragon0501** [comment]
Nachdem ich den Fehler im Skript festgestellt habe habe ich unverzüglich die 1.6.6 installiert. entschuldige....
