### ISSUE TITLE
Meldung beim Start vom Script

### ISSUE THREAD

**Issue by mymeyer** [Pittini/iobroker-Fensterauswertung#26]
Hallo, bekomme folgende Meldung wenn ich das Script startet. Räume und Funktionen sind bereits angelegt.
Hier das Log:

`

javascript.0 | 2021-02-07 21:31:27.895 | error | (10172) at Script.runInContext (vm.js:130:18)
-- | -- | -- | --
javascript.0 | 2021-02-07 21:31:27.895 | error | (10172) at script.js.common.FensterTuerCheck:1410:3
javascript.0 | 2021-02-07 21:31:27.895 | error | (10172) at script.js.common.FensterTuerCheck:136:67
javascript.0 | 2021-02-07 21:31:27.895 | error | (10172) script.js.common.FensterTuerCheck: TypeError: Cannot read property 'enumNames' of null
javascript.0 | 2021-02-07 21:31:27.894 | info | (10172) script.js.common.FensterTuerCheck: registered 0 subscriptions and 0 schedules

`
Kannst Du mir weiterhelfen ?

MyMeyer

**Comment by Pittini** [comment]
Hast Du den JS Controller neugestartet nach dem anlegen der Funktionen Tuer und Fenster? Die Meldung sagt dass das Skript nen Problem mit ner Aufzählung hat.

**Comment by mymeyer** [comment]
Habe ich gemacht. Ich habe das Log nochmal erweitert. Das ist noch was anderes. Weiß aber nicht wo das herkommt.

`
javascript.0 | 2021-02-08 21:55:47.371 | info | (7907) Stop script script.js.common.FensterTuerCheck
-- | -- | -- | --
javascript.0 | 2021-02-08 21:55:44.473 | error | (7907) at Script.runInContext (vm.js:130:18)
javascript.0 | 2021-02-08 21:55:44.473 | error | (7907) at script.js.common.FensterTuerCheck:1410:3
javascript.0 | 2021-02-08 21:55:44.473 | error | (7907) at script.js.common.FensterTuerCheck:136:67
javascript.0 | 2021-02-08 21:55:44.472 | error | (7907) script.js.common.FensterTuerCheck: TypeError: Cannot read property 'enumNames' of null
javascript.0 | 2021-02-08 21:55:44.469 | info | (7907) script.js.common.FensterTuerCheck: registered 0 subscriptions and 0 schedules
**### javascript.0 | 2021-02-08 21:55:44.454 | warn | (7907) Object "javascript.0.Heizung.Fenster.Buero" does not exist**
javascript.0 | 2021-02-08 21:55:44.454 | info | (7907) script.js.common.FensterTuerCheck: starting Fensterskript, Version 1.6.7
javascript.0 | 2021-02-08 21:55:44.436 | info | (7907) Start javascript script.js.common.FensterTuerCheck
`


Muss mal sehen wo ich **Javascript.0.Heizung.Fenster.Buero** löschen kann. Weil unter Objekte gibt es den Pfad nicht.

**Comment by Pittini** [comment]
> Weil unter Objekte gibt es den Pfad nicht.

Aber gab es evtl. mal? Dann könnte ne Leiche in der Raum und/oder Funktionenaufzählung das Problem verursachen. Geh mal direkt in die Aufzählungen und kontrollier ob Du dort was nicht existentes findest.

**Comment by mymeyer** [comment]
Hi, ja ich habe es gefunden. Noch ne Leiche im Keller gehabt :-)
Close Error.
