### ISSUE TITLE
Lüften - Erinnerung

### ISSUE THREAD

**Issue by n3roGit** [Pittini/iobroker-Fensterauswertung#3]
Super Script!
Was noch cool wäre, ist eine Benachrichtigung, wenn man das Fenster mehr als z.B. 24 nicht geöffnet hatte direkt in dem generierten HTML.

Aktuell habe ich das als Blockly als Extra Text gebaut.
https://pastebin.com/raw/VGswGe56

**Comment by Pittini** [comment]
> Was noch cool wäre, ist eine Benachrichtigung, wenn man das Fenster mehr als z.B. 24 nicht geöffnet hatte direkt in dem generierten HTML.

Finde ich grundsätzlich ne gute Idee, aber nicht pauschal. Müsste man dann pro Raum an-ausschalten können und verschiedene Zeiten setzen können. Weil ich hab z.B. am Dachbodenfenster nen Sensor, aber ich will ganz sicher nicht täglich denn Dachboden lüften. Und die Werkstatt langt einmal die Woche wenn ich nichts drin werkle, usw. Heißt zusätzliche Datenpunkte, aber ich denke ich werds reinbauen, is sinnvoll.

**Comment by n3roGit** [comment]
Ja natürlich. Finde ich super! Dank dir!

**Comment by Pittini** [comment]
implemented with [V1.3](https://github.com/Pittini/iobroker-Fensterauswertung/blob/master/Fensterauswertung-V1.3.0-beta.js)
