### ISSUE TITLE
Pull Request: Alexa Lautstärke mitgeben / PushOver Device mitgeben und Titel eingefügt

### ISSUE THREAD

**Issue by Screambear** [Pittini/iobroker-Fensterauswertung#30]
const PushoverDevice = ""; // An welches Gerät sollen Nachrichten via PushOver gesendet werden? Leer an alle Geräte.
const AlexaVolume = "50"; // Lautstärke der Nachrichten. Wert von 1 bis 100 

if (UseAlexa) {
                if (AlexaId != "" && AlexaVolume != "") setState("alexa2.0.Echo-Devices." + AlexaId + ".Commands.announcement"/*announcement*/, AlexaVolume + "; " + msg);
};

if (UsePushover) {
                sendTo("pushover", "send", {
                    device: PushoverDevice, message: msg, title: "Fensterüberwachung", sound: ""
                });
};

**Comment by Pittini** [comment]
Implemented with 1.6.9

**Comment by Screambear** [comment]
Super danke! In Zeile 379 ist noch ein "Fehler" dort im pushover Titel wird nicht die variable sondern ein fester Text benutzt.

**Comment by Pittini** [comment]
Danke, ist behoben (keine neue Version)
