### ISSUE TITLE
Datenpunkt RoomsWithVentWarning wird nicht gefüllt

### ISSUE THREAD

**Issue by stony2k** [Pittini/iobroker-Fensterauswertung#31]
Ich habe fürs Wohnzimmer eine Lüftungswarnung aktuell für alle 3:50 Min eingestellt. Als Benachrichtigung bekomme ich auch eine E-Mail. Leider wird der entsprechende Datenpunkt nicht gefüllt. Ich würde diesen gerne nutzen um meine Lampen rot zu färben.

Könnte man das zeitnah fixen?
![Screenshot 2021-04-04 171239](https://user-images.githubusercontent.com/16526471/113513245-07ce5700-9569-11eb-9bcd-c2460d5f32c5.jpg)

**Comment by Pittini** [comment]
Kann ich leider nicht reproduzieren, hier läuft das. Bitte mal komplettes startlog mit aktiviertem logging und dann warten bis ne Ventmsg kommt und dann auch das log.

![2021-04-05 11_26_32-Window](https://user-images.githubusercontent.com/51408942/113559627-043ade80-9602-11eb-8c13-7dd14db7221d.png)

**Comment by stony2k** [comment]
Ich habe, ähnlich wie du, die VentWarnTime noch viel tiefer gestellt: Auf 5 Minuten und der Datenpunkt wurde gefüllt. Jetzt zum Testen auf 1 Minute und es klappt auch. Jetzt setze ich die Nachricht mal 2 h hoch. Kann es sein, dass ab VentWarnTime > 2 - 3 h das Script nicht richtig arbeitet.

**Comment by Pittini** [comment]
> Kann es sein, dass ab VentWarnTime > 2 - 3 h das Script nicht richtig arbeitet?

Unwahrscheinlich, is ja immer der selbe Code, dieselbe Funktion, egal ob das ne Minute oder ne Stunde is Aber mal sehen was die 2h bei Dir machen. Und solange es klappt, helfen die Logs natürlich nix, weil da seh ich dann ja nur dasses klappt ;)

**Comment by stony2k** [comment]
Test mit 0,16 Tagen ~ 4h. Es funktioniert. Frag mich nicht was da los war. Vielen Dank.
