### ISSUE TITLE
Speaker short louder before announcement

### ISSUE THREAD

**Issue by cobra98** [Pittini/iobroker-Fensterauswertung#36]
When alexa announces "Schlafzimmer Fenster geschlossen or geöffnet" if music plays on one speak it suddenly goes loud short, the message works normal. 
I tried changing 
"const AlexaVolume = "1"; // Lautstärke der Nachrichten. Wert von 1 bis 100" but no difference.
I use the serial for AlexaID for "Überall" to have the message on each speaker always.
I was wondering if i can solve it somehow that the speakers not short change their volume specially in the evening/night.

**Comment by Pittini** [comment]
Thats maybe a Alexa Issue, nothing i can do in the script as far as I know. The Alexa call is one line in the code, i think theres no problem from scriptside.
