### ISSUE TITLE
Lüftungswarnung bei geöffneter Türe. 

### ISSUE THREAD

**Issue by slimline33** [Pittini/iobroker-Fensterauswertung#37]
Ich habe im Wohnzimmer eine Terrassentür und ein Fenster.

Leider verschwindet die Lüftungswarnung nicht wenn die Türe geöffnet wurde. 

![IMG_20210625_212020](https://user-images.githubusercontent.com/3323812/123475280-761c3600-d5fb-11eb-9799-b2d1a72d25f9.jpg)

Evtl kann man das so steuern.

Gruß bimmi

**Comment by Pittini** [comment]
Ja, das is so implementiert. Türen setzen die Lüftungswarnung nicht zurück, weil wenn jemand kommt/geht is ja noch lang ned gelüftet. Das Thema Terassentür is mir bewußt, aber beides geht imho nicht.

**Comment by slimline33** [comment]
Okey. Dann ist es eben so 😀

Gruß bimmi
