### ISSUE TITLE
weitere Konfiguration PushOverSound

### ISSUE THREAD

**Issue by onlyKlausM** [Pittini/iobroker-Fensterauswertung#38]
kannst du das vielleicht in einer nächsten Version einbauen  ?
bspw:    const PushOverSound = "magic";
vielen Dank !

**Comment by Pittini** [comment]
Mach ich gerne, aber mit der const isses ja vermutl. nicht getan, das muß ja auch iwo verwendet werden. Ich nutze kein Pushover und hab keine Ahnung wie das aussehen muß, bitte nen komplettes Codesnippet machen, dann is das morgen drin.

**Comment by onlyKlausM** [comment]
Bei mir Zeile 383:

 if (UsePushover) {
                sendTo("pushover", "send", {
                    device: PushoverDevice, message: msg, title: PushOverTitle, **sound: PushOverSound**
                });
            };

**Comment by Pittini** [comment]
Ok, soweit klar, aber eine Frage noch. Wenn kein Sound gewünscht, genügt es dann die const PushOverSound auf "" zu stellen, oder muß das dann komplett raus, also das oben fette weg?

**Comment by onlyKlausM** [comment]
vielen Dank für die Bereitschaft, ich war heute morgen im kurz angebunden :-)
Ohne Sound wäre "none" . Der Leerstring erzeugt den Default Sound.

**Comment by Pittini** [comment]
So, sollte jetzt drin sein, hab auch noch gesehen dass die Instanz nicht genutzt wurde und das gleich mit korrigiert. Bitte kurz testen.

**Comment by onlyKlausM** [comment]
es ist leider brechend heiß hier im Büro .. ich muss abbrechen die Ursache zu suchen.
meine Konfiguration:
```
//Pushover
const UsePushover = true; // Sollen Nachrichten via PushOver gesendet werden?
const PushoverInstance = "pushover.0"; //Pushoverinstanz welche genutzt werden soll angeben
const PushoverDevice = "All"; //Welches Gerät soll die Nachricht bekommen
const PushOverTitle = "Überwachung";
const PushOverSound = "none";
```
und Programmteil ab _//Ab hier nix mehr ändern!_ übernommen erzeugt nun hier Fehler.

```
(1049) at Object.<anonymous> (script.js.Visualisierung.RH2.Fensterauswertung:1362:25)
(1049) at CheckWindow (script.js.Visualisierung.RH2.Fensterauswertung:988:64)
(1049) at Meldung (script.js.Visualisierung.RH2.Fensterauswertung:380:24)
(1049) Error in callback: ReferenceError: PushOverInstance is not defined`
```

![image](https://user-images.githubusercontent.com/59437453/123855862-aaa43080-d920-11eb-9447-86722d07ec4a.png)

**Comment by Pittini** [comment]
Pushover vs. PushOver, das hab ich im update korrigiert, Du aber scheinbar nicht.

**Comment by onlyKlausM** [comment]
genau so war's, vielen Dank !
