### ISSUE TITLE
Lüftungswarnung? -> Vorschlag: Lüftungsempfehlung?

### ISSUE THREAD

**Issue by slimline33** [Pittini/iobroker-Fensterauswertung#40]
Hi, nur als Vorschlag: https://forum.iobroker.net/topic/2313/skript-absolute-feuchte-berechnen

Man könnte doch anstatt nur zu warnen, dass seit X Tagen nicht mehr gelüftet wird, auch diese Lüftungswarnung mit ins Skript einbinden.

Gruß Christoph

**Comment by Pittini** [comment]
Duplicate Issue with https://github.com/Pittini/iobroker-Fensterauswertung/issues/24
