### ISSUE TITLE
Festlegen von Zeiten, in denen keine Sprachausgabe erfolgt

### ISSUE THREAD

**Issue by Choqui22** [Pittini/iobroker-Fensterauswertung#42]
Das Skript ist spitze, es wäre jedoch toll wenn man die Sprachausgabe auf gewisse Zeiten einschränken könnte.

**Comment by stony2k** [comment]
Du kannst über den Datenpunkt **MuteMode** das Script stummschalten. Am einfachsten zeitgesteuert per Blockly :)

Siehe Punkt 7 der Installation

```
0 = Alle Ansagen werden ausgegeben.
1 = "Stumme" Nachrichten via Telegram/Mail etc. werden ausgegeben, Sprachausgaben geblockt.
2 = Alle Nachrichten werden geblockt.

**Comment by Pittini** [comment]
Wie @stony2k  schon schrieb. Passendes Timerskript findest bei meinen Repos.
