### ISSUE TITLE
Fensterüberwachung ohne Kopfzeile?

### ISSUE THREAD

**Issue by heinog** [Pittini/iobroker-Fensterauswertung#43]
Ich habe das Problem, das ich die Kopfzeile mit geöffnetten Fenster und Türen nicht haben möchte.
Daraufhin habe ich die Zeile "const ShowSummaryTbl = true; // Zusammenfassung anzeigen?" auf false gesetzt.
Die Anzeige oben ist dann auch weg, erscheint aber sporadisch immer kurzzeitig wieder. Die Javascript instance habe ich auch schon neu gestartet, aber hat nichts gebracht. Was mache ich falsch?

**Comment by Pittini** [comment]
Wenn ausgeschaltet und trotzdem (mnchmal) sichtbar, vermute ich eine Browser Cache Problematik, o.ä. Wenn Du das in den Einstellungen deaktiviert hast, wird der Code ja nimmer generiert, iwoher muß das dann (vermutlich mit alten Daten) wieder reingemogelt werden. Schau mal ob das bei jedem Browser so ist.

**Comment by heinog** [comment]
Habe ich probiert, den Cache gelöscht, ohne Erfolg. Dieses ist bei Firefox und Google Chrom identisch

**Comment by Pittini** [comment]
Kann ich leider nicht reproduzieren, sowohl ShowSummaryTbl als auch ShowDetailTbl machen genau wasse sollen. Hab grad keine Idee was das bei Dir sein könnte, das Skript is zig mal im Einsatz, wenn da ein Prob wäre, hätte das auch wer anders sicher schon gemeldet. Soll heißen, ich vermute den Fehler bei Deiner Konfig.

**Comment by heinog** [comment]
Ich habe die Instanz Javascript und die dazugehörigen Objekte komplett gelöscht. Danach Javascript wieder installiert und ein Backup von den Scripten zurüchgespielt. Danach lief alles so wie es sein sollte.
Trotzdem Danke
