### ISSUE TITLE
Open Windows Message over 15 minutes

### ISSUE THREAD

**Issue by cobra98** [Pittini/iobroker-Fensterauswertung#46]
before 1.6.15 i only got a message when a windows was open for 15 minutes, now it seems to give this information every 10 minutes and adds 10 minutes. like open for 20 minutes (maybe it is another count but it seems not stop until the window is closed)

**Comment by Pittini** [comment]
Control Line 19,20,22. There was no change in 1.6.15 what can produce such a behaviour.

**Comment by cobra98** [comment]
Strange
const TimeToWindowMsg = 900000 // 300000 ms = 5 Minuten - Zyklus- bzw. Ablaufzeit für Fenster-offenwarnung/en
const TimeToDoorMsg = 300000 // 300000 ms = 5 Minuten - Zyklus- bzw. Ablaufzeit für Tür-offenwarnung/en

is set, it seems not stop to message the window is open
How can i set to only announce it is open and then only once 15 minutes is open, then nothing else anymore?
(Worked before like that)

**Comment by cobra98** [comment]
The error after opening and closing is normal?

```
04:07:18.446 | error | javascript.0 (1628) at Meldung (script.js.common.Fensterauswertung:395:17)
-- | -- | --
04:07:18.446 | error | javascript.0 (1628) at CheckWindow (script.js.common.Fensterauswertung:1086:64)
04:07:18.446 | error | javascript.0 (1628) at Object.<anonymous> (script.js.common.Fensterauswertung:1388:25)
04:07:37.846 | error | javascript.0 (1628) at Meldung (script.js.common.Fensterauswertung:395:17)
04:07:37.846 | error | javascript.0 (1628) at CheckWindow (script.js.common.Fensterauswertung:1014:64)
04:07:37.846 | error | javascript.0 (1628) at Object.<anonymous> (script.js.common.Fensterauswertung:1388:25)

```

**Comment by Pittini** [comment]
> The error after opening and closing is normal?

No, it isn't. This error mostly comes because of misconfiguration in Line 42 and/or 43. Please check. Both have to be false.

**Comment by cobra98** [comment]
i corrected now line 43 and music studio issue is solved
I will see if the message also stops after 15 minutes window is still open, hopefully 
(as i leave window over night in summer)

**Comment by cobra98** [comment]
Problem durch ein Iobroker updaten behoben
