### ISSUE TITLE
Fehlermeldung des Skriptes

### ISSUE THREAD

**Issue by fzoellne** [Pittini/iobroker-Fensterauswertung#49]
Hallo,

habe das Skript nach Anleitung installiert, wenn ich ein Fenster öffne registriert das Script dies und setzt die entsprechenden Datenpunkte. Wenn ich dann das Fenster wieder schließe wird eine Fehlermeldung geworfen:

vascript.0 | 2023-02-18 18:02:03.727 | error | at processTimers (node:internal/timers:502:7)
-- | -- | -- | --
javascript.0 | 2023-02-18 18:02:03.727 | error | at listOnTimeout (node:internal/timers:559:17)
javascript.0 | 2023-02-18 18:02:03.726 | error | at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:2613:34)
javascript.0 | 2023-02-18 18:02:03.726 | error | at Object.<anonymous> (script.js.Monitoring.Fensterüberwachung:1388:25)
javascript.0 | 2023-02-18 18:02:03.726 | error | at CheckWindow (script.js.Monitoring.Fensterüberwachung:1014:64)
javascript.0 | 2023-02-18 18:02:03.725 | error | at Meldung (script.js.Monitoring.Fensterüberwachung:395:17)

Im Script wird an Zeile 395 die Funktion WriteEventLog(msg); aufgerufen. Scheint er nicht zu kennen?

Zum System: 
Plattform: docker
Node.js: v16.19.0
NPM: 8.19.3
JS Adapter 6.2.0

**Comment by Pittini** [comment]
Zeile 42+43 auf false.

**Comment by fzoellne** [comment]
Great, worked thanks
