### ISSUE TITLE
Erweiterung: Alexa-Ansage, ... nur unter Bedingungen

### ISSUE THREAD

**Issue by do1osc** [Pittini/iobroker-Fensterauswertung#5]
Hallo,

Eine Erweiterungsidee wäre das Ausgaben, z.B Alexa, Mail, Say, Telegramm,... Nur unter bestimmten Bedingungen ausgegeben werden.
Zum Beispiel, wenn ein DP größer oder kleiner dem Wert X ist.

Beispiele wären, Temperaturen, Anwesenheit,...

Mit freundlichen Grüßen, Sven

**Comment by Pittini** [comment]
Ich verstehe das Anliegen. Es macht aber  imho wenig Sinn das direkt in das Skript einzubauen, bzw. bräuchte man das dann in jedem Skript das derartige Ausgaben macht.
Die Lösung dafür heißt globales Skript welches quasi zentral alle Nachrichten managed. Dieses heißt bei mir z.B. Say (falls Du Dich schon gefragt hast was dieses UseSay in meinen Skripten bedeutet).
Dort wird z.B. via Timer von 22:00 bis 8:00 ein Ruhemodus aktiviert. Dort wird auch meine Stereoanlage während Ansagen gemutet, usw. Und dort könnte man genauso zentral auf Anwesenheit etc. reagieren.
Zusätzlich hat es den Vorteil das man bei Anpassungen nur an einer Stelle ändern muß und nicht in jedem Skript Änderungen nötig sind.
Lange Rede, kurzer Sinn, das wird es in diesem Skript nicht geben.
