### ISSUE TITLE
Erweiterte Lüftungsempfehlung implimentieren

### ISSUE THREAD

**Issue by dike1982** [Pittini/iobroker-Fensterauswertung#50]
Das Skript läuft soweit, Vielen Dank für die Arbeit.

Das Thema Lüftung könnte man noch ausbauen in dem man nicht die Zeit als Maßstab zur Lüftung verwendet sondern die tatsächliche Luftfeuchte des Raums.
Es gibt hier bereits ein Skript:
https://github.com/foxriver76/iot-blog-scripts

Wenn man beide Funktionalitäten kombinieren könnte wäre das glaube ich ein echter Mehrwert!

**Comment by Pittini** [comment]
Wurde vor längerem schon mal gewünscht. Heute gleiche Antwort wie damals: Das Skript soll Anfängertauglich bleiben und ist eh schon recht komplex. Wenn jetzt auch noch Feuchtefühler für unterschiedliche Räume und aussen, inkl diverser Einstellmöglichkeiten, dazukommen, wird das imho zu komplex. Nichtsdestotrotz sind wir ja im open source Bereich, kann gerne jemand forken und das implementieren.
