### ISSUE TITLE
error Meldung im log

### ISSUE THREAD

**Issue by ug0box** [Pittini/iobroker-Fensterauswertung#51]
Seit neustem kommt folgende Fehlermeldung ausgelöst durch das Script.

error: javascript.0 (19082) Script script.js.Fensterstatus is calling setState more than 1000 times per minute! Stopping Script now! Please check your script!

**Comment by crusader85** [comment]
Ja, das passiert meistens, wenn du einen Sensor hast, bei dem der Raum nicht gesetzt ist. Schau mal da bitte nach, ob da alle Räume wie in der Anleitung gesetzt sind. Es reicht schon ein falsch konfigurierter Sensor und so was passiert

**Comment by ug0box** [comment]
Ich hatte überall bei den Objecten/Devices den Status (Tüt bzw. Fenster)gesetzt. Habe das nun mal geändert.
Wollte aber 1 Device nicht mit einlesen lassen, da ein Sensor als Klingel funktioniert und immer offen ist, außer wenn es klingelt, nun bekomme ich pausenlos die Meldung das dieser Sensor (Tür) offen ist.

**Comment by ug0box** [comment]
Ich habe es gefunden, einfach dort Status raus. Jetzt ist ruhe, einfach mal beobachten. Ist schon komisch, das Script lief jahrelang ohne Probleme und Fehler und ich hatte auch nichts geändert.
Mal abwarten.
Danke erstmal für die Hilfe.

**Comment by ug0box** [comment]
Hallo, seit letzten Updates, Javascript und Admin kommt folgende Warnmeldung:
![image](https://github.com/Pittini/iobroker-Fensterauswertung/assets/157954989/5ab5a240-6dc2-4d4f-8a45-4fe98921b760)
Muss ich irgendwas umstellen oder kann ich das einfach ignorieren?

**Comment by Pittini** [comment]
> Hallo, seit letzten Updates, Javascript und Admin kommt folgende Warnmeldung:... Muss ich irgendwas umstellen oder kann ich das einfach ignorieren?

Ich würde mal auf ne Fehlkonfiguration tippen, welche schon immer da war, aber erst jetzt gemeldet wird (durch iein update). Prüf mal ob Du wirklich nur einzelnen Stati die Funktion Tür oder Fenster gegeben hast oder ganzen Geräten/Objektbäumen. Prüfe auch ob überall Räume zugewiesen sind und keine Nullwerte iwo drinstehen.

**Comment by ug0box** [comment]
> > Hallo, seit letzten Updates, Javascript und Admin kommt folgende Warnmeldung:... Muss ich irgendwas umstellen oder kann ich das einfach ignorieren?
> 
> Ich würde mal auf ne Fehlkonfiguration tippen, welche schon immer da war, aber erst jetzt gemeldet wird (durch iein update). >Prüf mal ob Du wirklich nur einzelnen Stati Funktion Tür oder Fenster gegeben hast oder ganzen Geräten/Objektbäumen. 

Ja, eben nochmal geschaut, nur den einzelnen Funktionen zugewiesen. 2 Kontakte wurden nicht zugewiesen, da sie 
mißbraucht wurden für andere Sachen.

>Prüfe auch ob überall Räume zugewiesen sind und keine Nullwerte iwo drinstehen.

Ja, jedem Objekt wurde ein Raum u.s.w. zugewiesen.

**Comment by ug0box** [comment]
![image](https://github.com/Pittini/iobroker-Fensterauswertung/assets/157954989/ae8cf6ae-5067-4496-89c8-02b05ef369e1)
![image](https://github.com/Pittini/iobroker-Fensterauswertung/assets/157954989/a98cae5e-6287-4d20-9db3-e5371e78c7ce)

**Comment by ug0box** [comment]
Hab eben auch festgestellt, das sich die Zahl erhöht.?
![image](https://github.com/Pittini/iobroker-Fensterauswertung/assets/157954989/4b325f95-a9e4-4142-be26-6b748d49fd89)

**Comment by Pittini** [comment]
Seltsam. Starte mal den JS Controller neu und gugg was dann kommt. Ich geh davon aus dasses kein Bug ist, sondern iwo bei Dir liegt, sonst hätten sich schon mehr Leute gemeldet, das Skript haben sehr viele im Einsatz.

**Comment by ug0box** [comment]
Ich denk auch das ich hier irgendwie nen Knoten drin habe. Hab nur kein Plan wie und wo.
Nach Neustart vom JS kommt nur:
![image](https://github.com/Pittini/iobroker-Fensterauswertung/assets/157954989/8fb8afad-afda-4a89-8273-e5b3c1a06c92)
ansonsten keine Warn -oder Fehlermeldungen.

**Comment by Pittini** [comment]
Schalt mal im Skript das logging an und poste mir was beim starten des Skriptes dann kommt (am besten das was unterm Skriptfenster steht, nicht im normalen log), evtl. seh ich da worans hängt.

**Comment by ug0box** [comment]
19.3.2024, 20:37:28.931	[info ]: javascript.0 (13710) Stop script script.js.Fensterstatus
19.3.2024, 20:37:49.854	[info ]: javascript.0 (19955) Start javascript script.js.Fensterstatus
19.3.2024, 20:37:49.870	[info ]: javascript.0 (19955) script.js.Fensterstatus: starting Fensterskript, Version 1.6.13
19.3.2024, 20:37:49.889	[info ]: javascript.0 (19955) script.js.Fensterstatus: registered 0 subscriptions, 0 schedules, 0 messages, 0 logs and 0 file subscriptions
19.3.2024, 20:37:50.838	[info ]: javascript.0 (19955) script.js.Fensterstatus: starting Fensterskript, Version 1.6.13
19.3.2024, 20:37:50.855	[info ]: javascript.0 (19955) script.js.Fensterstatus: starting Fensterskript, Version 1.6.13
19.3.2024, 20:37:50.871	[info ]: javascript.0 (19955) script.js.Fensterstatus: starting Fensterskript, Version 1.6.13
19.3.2024, 20:37:50.884	[info ]: javascript.0 (19955) script.js.Fensterstatus: starting Fensterskript, Version 1.6.13
19.3.2024, 20:37:50.895	[info ]: javascript.0 (19955) script.js.Fensterstatus: starting Fensterskript, Version 1.6.13
19.3.2024, 20:37:50.905	[info ]: javascript.0 (19955) script.js.Fensterstatus: starting Fensterskript, Version 1.6.13
19.3.2024, 20:37:50.915	[info ]: javascript.0 (19955) script.js.Fensterstatus: starting Fensterskript, Version 1.6.13
19.3.2024, 20:37:51.220	[warn ]: javascript.0 (19955) script.js.Fensterstatus: More than 100 subscriptions registered. Check your script!
19.3.2024, 20:37:51.251	[warn ]: javascript.0 (19955) script.js.Fensterstatus: More than 200 subscriptions registered. Check your script!
19.3.2024, 20:37:51.282	[warn ]: javascript.0 (19955) script.js.Fensterstatus: More than 300 subscriptions registered. Check your script!

**Comment by Pittini** [comment]
Da sollte deutlich mehr stehen wenn Du das logging im Skript aktiviert hast.

**Comment by ug0box** [comment]
> Da sollte deutlich mehr stehen wenn Du das logging im Skript aktiviert hast.

ja, sorry.
[20 3 2024 18 41 41 887.txt](https://github.com/Pittini/iobroker-Fensterauswertung/files/14715710/20.3.2024.18.41.41.887.txt)

**Comment by ug0box** [comment]
> > Da sollte deutlich mehr stehen wenn Du das logging im Skript aktiviert hast.
> 
> ja, sorry. [20 3 2024 18 41 41 887.txt](https://github.com/Pittini/iobroker-Fensterauswertung/files/14715710/20.3.2024.18.41.41.887.txt)

[3 22 2024 10 19 56 AM.txt](https://github.com/Pittini/iobroker-Fensterauswertung/files/14720640/3.22.2024.10.19.56.AM.txt)
