### ISSUE TITLE
Homematik Tilted windows

### ISSUE THREAD

**Issue by dos1973** [Pittini/iobroker-Fensterauswertung#6]
Could you please add DP for tilted Windows. (Homematik)

**Comment by Pittini** [comment]
Support for tilted windows is already added since 1.2.3. But what do you mean with an DP for that?

**Comment by dos1973** [comment]
keine Ahnung, warum ich meinen Text nicht in Deutsch verfasst habe...

ich meine die Unterscheidung der gekippten Fenster als eigener Datenpunkt.
Derzeit werden die gekippten zu den offenen gezählt. Für mich sind gekippte Fenster anders zu bewerten als offene (Gartenzugang), Gekippte Fenstern würde ich gerne in meinem VIS anders visualisieren als offene.

**Comment by Pittini** [comment]
> ich meine die Unterscheidung der gekippten Fenster als eigener Datenpunkt.
> Derzeit werden die gekippten zu den offenen gezählt. Für mich sind gekippte Fenster anders zu bewerten als offene (Gartenzugang),

Verstehe. Das ist nicht unerheblicher Aufwand, da das Skript raumbezogen arbeitet. Das zu integrieren würde bedeuten pro Raum zwei weitere Datenpunkte zu erstellen (IsTilted und RoomTiltedCount) und einen zusätzlichen Datenpunkt im Skriptrootbereich (RoomsWithTiltedWindows). Weiterhin stellt sich die Frage ob gekippte Fenster dann bei den offenen mitgezählt werden oder nicht. Ich denk mal drüber nach, aber jedenfalls ist das nix was mal eben schnell kommen wird, da sind etliche Strukturänderungen im ganzen Skript nötig, da das erste was das Skript macht ist, dasses gekippt mit offen ersetzt und intern nur mit offen oder zu arbeitet.
Zusätzlich werden alle Meldungen verdoppelt, weil man ja mehrere Fenster bzw. mehrflügelige Fenster haben kann. Was wenn eines offen, und eines gekippt ist? Wie soll gekippt bei der Lüftungswarnung behandelt werden?

**Comment by Pittini** [comment]
Implementiert mit V 1.5.0
