### ISSUE TITLE
Error Log

### ISSUE THREAD

**Issue by n3roGit** [Pittini/iobroker-Fensterauswertung#8]
Ich nochmal. Irgendwie bekomme ich weiterhin die folgende Meldung.

`

09:32:43.720 | error | javascript.0 (1144) at Meldung (script.js.System.WindowWatcher:173:21)
-- | -- | --
09:32:43.720 | error | javascript.0 (1144) at VentCheck (script.js.System.WindowWatcher:333:21)
09:32:43.720 | error | javascript.0 (1144) at init (script.js.System.WindowWatcher:153:9)
09:32:43.721 | error | javascript.0 (1144) at main (script.js.System.WindowWatcher:160:5)
09:32:43.721 | error | javascript.0 (1144) at Object.<anonymous> (script.js.System.WindowWatcher:129:13)

`

**Comment by Pittini** [comment]
Und immer noch bringt mir das Log da nix. Is sehe in welcher Funktion der Fehler auftaucht aber ohne die Begleitumstände zu kennen hilft mir das nicht.  Ich hab Dir doch im anderen Thread (den ich zumachen sollte) geschrieben was ich brauch. Also nochmal:
Wann bzw. unter welchen Umständen tritt der Fehler auf. Komplettes Infolog des Skriptes zu diesem Zeitpunkt. Screenshot des aufgeklappten LogChannels. Screenshot eines Deiner für das Skript konfiguriereten DAtenpunktes.

**Comment by n3roGit** [comment]
Settings:
https://pastebin.com/raw/70fXqws8

DPs
![image](https://user-images.githubusercontent.com/8565847/79314931-a732ae00-7f02-11ea-8a79-243ec7952f1d.png)

Log ab restart:
https://pastebin.com/raw/cgKvb1pv

Problem:
Der Fehler kommt direkt nach dem start des Scripts

**Comment by n3roGit** [comment]
Debug Log:
https://pastebin.com/raw/eNSLrGWR

**Comment by Pittini** [comment]
Danke. Jetzt seh ich dass der Fehler bei der Meldungsausgabe passiert (Badezimmer nicht gelüftet) und wenn ich mir die Settings ansehe, sehe ich:

const UseSay = true; // Sollen Nachrichten via Say ausgegeben werden? Autorenfunktion, muß deaktiviert werden.

Stell das mal auf false. Dann Feedback bitte.

**Comment by n3roGit** [comment]
Das hatte ich garnicht gesehen... GEHT! 1000 Dank!
