### ISSUE TITLE
HTML Grafik (flapping)

### ISSUE THREAD

**Issue by n3roGit** [Pittini/iobroker-Fensterauswertung#9]
Richtiger Inhalt:
![2020-04-16 09_42_59-Window](https://user-images.githubusercontent.com/8565847/79428691-ceeb4a00-7fc6-11ea-9ddd-3731ecbdfd1e.png)
Kurzzeitige falsche Grafik:
![2020-04-16 09_42_55-Window](https://user-images.githubusercontent.com/8565847/79428693-cf83e080-7fc6-11ea-908f-6d40a18d66f5.png)

Moin moin,

das Skript läuft mittlerweile ziemlich rund. Mir ist allerdings aufgefallen, dass die Grafik dazu zwischendurch immer kurz die Inhalte auf "bitte lüften" ändert und danach wieder den korrekten inhalt anzeigt,

Dieser Moment dauert ca. 1 Sekunde und ist regelmäßig zu sehen.

Allerdings wird bei dem Wechsel keine Benachrichtigung geschickt (was ja auch korrekt ist).

**Comment by n3roGit** [comment]
PS: Im Log sehe ich keine Ausgabe bei dieser Änderung.

**Comment by n3roGit** [comment]
![2020-04-17 08_53_26-Window](https://user-images.githubusercontent.com/8565847/79540846-176b3c00-8089-11ea-97cb-1595b6cb14eb.png)
![2020-04-17 08_53_55-Window](https://user-images.githubusercontent.com/8565847/79540849-1803d280-8089-11ea-9905-10e85656ff9b.png)

Mir ist auch aufgefallen, dass die Lüftungsbenachrichtigung teilweise falsch ausgegeben wird. z.B. wurde vorhin die Meldung ausgegeben während das Fenster auf war.

Im Schlafzimmer ist das Fenster nun ~30 Minuten zu aber das Script meint es müsse noch gelüftet werden.

**Comment by Pittini** [comment]
> Dieser Moment dauert ca. 1 Sekunde und ist regelmäßig zu sehen.
> 
> Allerdings wird bei dem Wechsel keine Benachrichtigung geschickt (was ja auch korrekt ist).

Ich vermute mal dass da ne Art Lag beim refreshen auftritt. Die Tabelle wird ja jede Minute neu berechnet und aufgebaut. Deshalb gibts auch keine Meldung und kein Log. Ich hab in der neuen Version die ich gleich hochlade mal nen Log reingemacht dann sieht man wann das passiert. Bei mir tritt das nicht auf.

Zum zweiten Problem, ja das hab ich ähnlich auch bemerkt und auch schon was geändert. Da das aber sehr sporadisch auftritt isses schwer sicher zu sagen obs jetzt passt, sollte aber.

**Comment by n3roGit** [comment]
Top ich danke dir. Ich werde es testen und berichten

**Comment by n3roGit** [comment]
Das scheint mit der jetzigen Version zu funktionieren!

Magst du vielleicht mal darüber nachdenken folgendes zu implementieren:

Die Warnung alle X Minuten bei geöffneten Fenster exponentiell zu verlängern. Gerade bei warmen Temperaturen möchte man manche Fenster ja gerne offen haben. 
Da wäre etwa wie 30 min, 1 h, 2h , keine weitere Benachrichtigung top.
Ebenso wäre es fein, wenn die AlsoMsgWinOpenClose erst bei einer Änderungszeit von z.b. einer Minute angesagt werden. Oft will man ja nur "eben" was von draußen holen oder ähnliches.


Beste Grüße und du macht hier nen klasse job.

**Comment by Pittini** [comment]
> Das scheint mit der jetzigen Version zu funktionieren!

Noch nicht ganz, ist besser geworden aber hakt noch an einer Stelle. Update kommt wenn der interne Test hier durch ist.

> Magst du vielleicht mal darüber nachdenken folgendes zu implementieren:

Wunsch eins - muß ich mal drüber nachdenken.
Wunsch zwei hab ich schon eingeplant weil das relativ leicht zu lösen sein dürfte. Aber mach bitt für jeden Wunsch nen eigenes Issue damits nicht untergeht.

**Comment by Pittini** [comment]
Fixed und Implementiert mit V 1.5.0
